accounts/urls.py
from django.urls import path
from .views import * 

from django.conf.urls import url
app_name = 'accounts'


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^alterar-dados/$', update_user, name='update_user'),
    url(r'^alterar-senha/$', update_password, name='update_password'),
    url(r'^registro/$', register, name='register'),
]

catalog/urls.py
from django.urls import path
from django.conf.urls import url
from . import views



urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^categoria/(?P<slug>.*)/$', views.category, name='category'),
    url(r'^produtos/(?P<slug>.*)/$', views.product, name='product'),
]

checkout/urls.py
import imp
from os import name
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'carrinho/adicionar/(?P<slug>.*)/$', views.create_cartitem, name='create_cartitem'),
    url(r'carrinho/$', views.cart_item, name='cart_item'),
    url(r'^finalizando/$', views.checkout, name='checkout'),
    url(r'^meus-pedidos/$', views.order_list, name='order_list'),
    url(r'^meus-pedidos/(?P<pk>.*)/$', views.order_detail, name='order_detail'),
]

ecommerce/urls.py
import imp
from django.contrib import admin
from django.urls import include
from django.views.generic.base import TemplateView
from app_ecommerce import views
from django.conf.urls import url

from django.contrib.auth.views import LoginView,  LogoutView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="index.html"), name='index'),
    url(r'^contato/$', views.contact, name='contact'),
    url(r'^entrar/$', LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^sair/$', LogoutView.as_view(), {'next_page':'index'},  name='logout'),
    url(r'^catalogo/', include(('catalog.urls', 'catalog' ), namespace='catalog')),
    url(r'^conta/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    url(r'^compras/', include(('checkout.urls', 'checkout'), namespace='checkout')),
    url(r'^admin/', admin.site.urls),
]

app_ecommerce/forms.py
from django import forms
from django.core.mail import send_mail
from django.conf import settings

class ContactForm(forms.Form):

    name = forms.CharField(label='Nome')
    email = forms.EmailField(label='E-mail')
    message = forms.CharField(label='Mensagem', widget=forms.Textarea)


    def send_mail(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        message = self.cleaned_data['message']
        message = 'Nome: {0}/nE-Mail:{1}/n{2}'.format(name, email, message)
        send_mail(
            'Contato Do Django E-Commerce', message, settings.DEFAULT_FROM_EMAIL,
            [ settings.DEFAULT_FROM_EMAIL ]
         )

app_ecommerce/views.py
# from django.core.exceptions import RequestAborted
from django.shortcuts import render

# from django.http import HttpResponse
from app_ecommerce.forms import ContactForm
from django.urls import reverse_lazy       
from django.contrib import messages
from catalog.models import Category
from django.core.mail import send_mail
from django.conf import settings
from django.views.generic import View, TemplateView, CreateView
from django.contrib.auth import get_user_model
User = get_user_model()



class IndexView(TemplateView):

    template_name = 'index.html'

index = IndexView.as_view()

def contact(request):
    success = False
    form = ContactForm(request.POST or None)
    if form.is_valid():
        form.send_mail()
        success = True
    elif request.method == 'POST':
        messages.error(request, 'Formulário inválido')
    context = {
        'form': form,
        'success': success
    }
    return render(request, 'contact.html', context)

app_ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>{% block title %}Mercado do djonho{% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<link rel="stylesheet" href="{% static 'assets/antigo/bootstrap.min.css' %}" media="screen" />
	<link rel="stylesheet" href="{% static 'assets/custom.min.css' %}" media="screen" />
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="{% url 'index' %}" class="navbar-brand">Mercado Do Djonho</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li>
              <a href="{% url 'index' %}">Início</a>
            </li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="{% url 'catalog:product_list' %}" id="download">Categorias <span class="caret"></span></a>
              <ul class="dropdown-menu" aria-labelledby="download">
				{% for category in categories %}
    <li><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
				{% endfor %}
              </ul>
            </li>
			<li>
				<a href="{% url 'contact' %}">Contato</a>
			</li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Sair</a></li>
            <li><a href="{% url 'accounts:index' %}">Configurar Conta</a></li>
            {% else %}
            <li><a href="{% url 'login' %}">Entrar</a></li>
            <li><a href="{% url 'accounts:register' %}">Registrar-se</a></li>
            {% endif %}
            <li><a href="{% url 'checkout:cart_item' %}">Carrinho</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="container">
      {% block messages %}
      {% for message in messages %}
      <div class="alert alert-{{ message.tags }}">
          {{ message }}
      </div>
      {% endfor %}
      {% endblock %}
      {% block container %}{% endblock %}
		<footer>
			<div class="row">
			  <div class="col-lg-12">
			    <ul class="list-unstyled">
			      <li class="pull-right"><a href="#top">Voltar ao Topo</a></li>
			      <li><a href="{% url 'index' %}">Início</a></li>
			      <li><a href="{% url 'catalog:product_list' %}">Produtos</a></li>
			      <li><a href="#">Produto</a></li>
			      <li><a href="#">Contato</a></li>
			      <li><a href="#">Termos e Privacidade</a></li>
			    </ul>
			  </div>
			</div>
		</footer>
	</div>
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'assets/bootstrap.min.js' %}"></script>
</body>
</html>

app_ecommerce/templates/contact.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
    Contato | {{ block.super }}
{% endblock %}

{% block container %}
<div class="page-header">
    <h1>Fale conosco</h1>
    {% if success %}
    <div class="alert alert-success">
      Mensagem enviada com sucesso
    </div>
    {% endif %}
    <form class="form-horizontal" action="" method="post" >
      {% csrf_token %}
        <fieldset>
            {% for field in form %}
            <div class="form-group{% if field.errors %} has-error {% endif %}">
              <label for="{{ field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
              <div class="col-md-9">
                {% render_field field class='form-control' %}
                {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
              </div>
            </div>
            {% endfor %}
            <div class="form-group">
              <div class="col-md-9 col-md-offset-3">
                <button type="submit" class="btn btn-primary">Enviar</button>
              </div>
            </div>
        </fieldset>
    </form>
</div>
{% endblock %}

app_ecommerce/templates/index.html
{% extends "base.html" %}

{% block container %}
<div class="jumbotron page-header">
  <h1>Comércio Livre</h1>
  <p>Projeto de Comércio Responsável e Seguro Para Venda De Produtos e Cursos a Preço Justo (atenção os valores estão na moeda yemne).</p>
  <p><a class="btn btn-primary" href="{% url 'catalog:product_list' %}" >Saiba mais</a></p>
</div>
{% endblock %}

app_ecommerce/templates/login.html
  
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}Entrar | {{ block.super }}{% endblock %}

{% block container %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <h1>Entrar</h1>
        </div>
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ error }}
            </div>
            {% endfor %}
            <fieldset>
                <div class="form-group{% if form.username.errors %} has-error{% endif %}">
                  <label for="{{ form.username.auto_id }}" class="col-md-3 control-label">{{ form.username.label }}</label>
                  <div class="col-md-9">
                    {% render_field form.username class="form-control" %}
                    {% for error in form.username.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                <div class="form-group{% if form.password.errors %} has-error{% endif %}">
                  <label for="{{ form.password.auto_id }}" class="col-md-3 control-label">{{ form.password.label }}</label>
                  <div class="col-md-9">
                    {% render_field form.password class="form-control" %}
                    {% for error in form.password.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">Enviar</button>
                  </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

app_ecommerce/templates/pagination.html
<head>
    <style>
        .paginator {
          display: inline-block;
          flex-grow: 1;
        }
        
        .paginator a {
          color: black;
          float: left;
          padding: 8px 16px;
          text-decoration: none;
          transition: background-color .3s;
          border: 1px solid #ddd;
        }
        .paginator li {
          list-style-type: none;
        }
        
        .paginator a.active {
          background-color: #4CAF50;
          color: white;
          border: 1px solid #4CAF50;
        }
        
        .paginator a:hover:not(.active) {background-color: #ddd;}
        </style>
</head>
<div class="row">
    <div class="col-md-12">
        <nav>
          <footer>
            <ul class="paginator">
                {% for page in paginator.page_range %}
                <li {% if page_obj.number == page %} class="active"{% endif %}><a href="?page={{ page }}{{ getvars }}">{{ page }}</a></li>
                {% endfor %}
            </ul>
          </footer>  
        </nav>
    </div>
</div> 